myFacegram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(("posts.urls", "posts"), namespace="posts")),
    
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(("posts.urls", "posts"), namespace="posts")),
    
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

urlpatterns = [
    path(
        route="",
        view=views.PostsFeedView.as_view(),
        name="feed"
    ),
    path(
        route="posts/new/",
        view=views.CreatePostView.as_view(),
        name="create"
    ),
    path(
        route="posts/<str:username>/<int:id>/",
        view=views.PostDetailView.as_view(),
        name="post"
    ),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path(
        route="login/",
        view=views.login_view,
        name="login"
    ),
    path(
        route="logout/",
        view=views.logout_view,
        name="logout"
    ),
    path(
        route="signup/",
        view=views.signup_view,
        name="signup"
    ),
    path(
        route="profile/update_profile",
        view=views.update_profile_view,
        name="update_profile"
    ),
    path(
        route="profile/<str:username>/",
        view=views.UserProfileView.as_view(),
        name="profile"
    ),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

    user=models.ForeignKey(User, on_delete=models.CASCADE)
    profile=models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title=models.CharField(max_length=255,blank=True,null=True)
    content_text=models.TextField(blank=False, null=False)
    photo=models.ImageField(upload_to='posts/pictures', null=True, blank=True)
    
    created=models.DateTimeField(auto_now_add=True)
    modified=models.DateTimeField(auto_now=True)

    def __str__(self):
        return (f'{self.title} by @{self.user.username}')
    

posts/forms.py
from django import forms

from posts.models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('user', 'profile', 'title','content_text', 'photo')

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, TemplateView, CreateView
from django.urls import reverse_lazy

from datetime import datetime

from posts.forms import PostForm
from posts.models import Post

class PostsFeedView(LoginRequiredMixin, ListView):
    """ Return all published posts. """
    template_name='posts/feed.html'
    model=Post
    ordering=("-created",)
    paginate_by=30
    context_object_name="posts"

class PostDetailView(LoginRequiredMixin, DetailView):
    """ Detail view for a post"""
    template_name='posts/post-detail.html'
    slug_field="id"
    slug_url_kwarg="username"
    pk_url_kwarg="id"
    queryset=Post.objects.all()
    context_object_name="post"

class CreatePostView(LoginRequiredMixin, CreateView):
    template_name="posts/new.html"
    form_class=PostForm
    success_url=reverse_lazy("posts:feed")
    def get_context_data(self, **kwargs):
        """Add user and profile to context"""
        context = super().get_context_data(**kwargs)
        context["created"] = datetime.today()
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile
        return context   

templates/posts/feed.html
{% extends 'base.html' %}

{% block title %}
  Posts
  {{ block.super }}
{% endblock %}

{% load static %}

{% block content %}
  <div class="container">
    {% block css %}
      <link rel="stylesheet" href="{% static 'css/posts/posts-grid.css' %}" />
    {% endblock %}
    <div class="posts-grid">
      {% for post in posts %}
        <div class="post-container">
          {% include 'posts/post.html' with post=post %}
          {% comment %} <div class="post p-4">
            <a href="{% url 'posts:post' post.user.username post.id %}" class="post-url"></a>
            <div class="post-header d-flex align-items-center">
              <a href="{% url 'users:profile' post.user.username %}" class="profile-picture user-picture">
                <div class="embed-responsive embed-responsive-1by1">
                  {% if post.profile.picture %}
                    <img class="rounded-circle embed-responsive-item rounded-circle" src="{{ post.profile.picture.url }}" alt="Picture profile of {{ post.user }}" />
                  {% else %}
                    <img class="rounded-circle embed-responsive-item rounded-circle" src="{% static 'img/user_logo.png' %}" alt="Picture profile of {{ post.user }}" />
                  {% endif %}
                </div>
              </a>
              <div class="post-data ml-2">
                <h4 class="">{{ post.user }}</h4>
                <span>{{ post.created }}</span>
              </div>
            </div>
            <div class="content-post">
              {% if post.title %}
                <h2 class="post-title mt-2 mb-0">{{ post.title }}</h2>
                <p class="mb-0">{{ post.content_text }}</p>
              {% else %}
                <p class="mt-1 mb-0">{{ post.content_text }}</p>
              {% endif %}

              {% if post.photo %}
                <img class="img-fluid mt-1 rounded post-photo" src="{{ post.photo.url }}" alt="Image blog: {{ post.title }}" />
              {% endif %}
            </div>
          </div> {% endcomment %}
        </div>
      {% endfor %}
    </div>
  </div>
  {% include 'pagination.html' %}
{% endblock %}
{% block script %}
  {{ block.super }}
  <script src="{% static 'js/modules/minimasonry.js' %}" type="module"></script>
  <script src="{% static 'js/posts/masonry.js' %}" type="module"></script>
{% endblock %}

templates/posts/new.html
{% extends 'base.html' %}

{% block title %}
  @{{ user.username }} | New Post
  {{ block.super }}
{% endblock %}

{% load static %}

{% block content %}
  {% block css %}
    <link rel="stylesheet" href="{% static 'css/posts/new.css' %}" />
    <link rel="stylesheet" href="{% static 'css/drag_and_drop.css' %}" />
    <link rel="stylesheet" href="{% static 'css/posts/posts-grid.css' %}" />
  {% endblock %}
  {% comment %}TODO Add breadcrumb navigation{% endcomment %}
  <div class="container">
    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="posts-grid">
        <div class="post-container">
          <div class="post-controls">
            <button class="btn btn-primary btn-rounded" type="submit" name="create_post">
              <div class="d-flex justify-content-center align-items-center">
                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-upload" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" />
                  <path fill-rule="evenodd" d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z" />
                </svg>
              </div>
            </button>
          </div>
          <div class="post create-post">
            <div class="post-content px-4 pt-4 pb-1">
              {% include 'posts/post-header.html' with user=user profile=profile created=created %}
              <input type="hidden" name="user" value="{{ user.pk }}" />
              <input type="hidden" name="profile" value="{{ profile.pk }}" />
              <div class="form-group">
                <h2 class="post-title form-control {% if form.title.errors %} is-invalid {% endif %}" id="title__editable" role="textbox" contenteditable>{% if form.errors %}{{ form.title.value }}{% endif %}</h2>
                <textarea hidden name="title" id="title"></textarea>
                <div class="invalid-feedback">
                  {% for error in form.title.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
                <span class="post-content form-control {% if form.content_text.errors %} is-invalid {% endif %}" id="content_text__editable" role="textbox" contenteditable>{% if form.errors %}{{ form.title.value }}{% endif %}</span>
                <textarea hidden name="content_text" id="content_text"></textarea>
                <div class="invalid-feedback">
                  {% for error in form.content_text.errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              </div>
            </div>

            <span class="btn btn-image btn-file square-image cursor-pointer p-0">
              <input onchange="onImageSelected(event)" type="file" placeholder="Imagen" id="photo" aria-describedby="photo" name="photo" class="form-control" required />
              <div for="photo" class="dropzone">
                <img src="{% static 'img/Photo_01.png' %}" />
                <span class="content-text">Arrastra aqui una imagen.</span>
              </div>
              <img alt="Imagen del evaluado" class="image-preview" id="image-preview" />
            </span>
            {% if form.photo.errors %}
              {% if invalidPhoto.type %}
                <div class="invalid-feedback">* El tipo de archivo no es válido.</div>
              {% endif %}
              {% if invalidPhoto.size %}
                <div class="invalid-feedback">* El tamaño de la imagen debe ser menor a 1MB.</div>
              {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}
{% block script %}
  {{ block.super }}
  <script src="{% static 'js/posts/new.js' %}"></script>
  <script src="{% static 'js/drag_and_drop.js' %}"></script>
  <script src="{% static 'js/modules/minimasonry.js' %}" type="module"></script>
  <script src="{% static 'js/posts/masonry.js' %}" type="module"></script>
{% endblock %}

templates/posts/post-content.html
{% load static %}
<div class="post-content
  {% if classes %}
    {{ classes }}
  {% else %}
    'px-4 py-4'
  {% endif %} ">
  {% include "posts/post-header.html" with user=post.user profile=post.profile created=post.created  %}
  {% if post.title %}
    <h2 class="post-title mt-2 mb-0">{{ post.title }}</h2>
    <p class="mb-0">{{ post.content_text }}</p>
  {% else %}
    <p class="mt-1 mb-0">{{ post.content_text }}</p>
  {% endif %}
</div>

templates/posts/post-detail.html
{% extends 'base.html' %}

{% block title %}
  @{{ post.user.username }} | Post - {{ post.id }}
  {{ block.super }}
{% endblock %}

{% load static %}

{% block content %}
  <div class="row justify-content-center">
    {% if post.photo %}
      <div class="col-lg-6 p-0">
        <div class="post p-4">
          {% if post.photo %}
            <img class="img-fluid mt-1 rounded post-photo" src="{{ post.photo.url }}" alt="Image blog: {{ post.title }}" />
          {% endif %}
        </div>
      </div>
    {% endif %}
    <div class="{% if post.photo %}
        
        col-lg-4

      {% else %}
        
        col-lg-5

      {% endif %} p-0">
      
      <div class="post p-4">
        {% include 'posts/post-content.html' with post=post %}
      </div>
    </div>
  </div>
{% endblock %}

templates/posts/post-header.html
{% load static %}
<a href="{% url 'users:profile' user.username %}" class="post-header d-flex align-items-center gap-1">
  <div class="profile-picture-container post-user-picture">
    {% if profile.picture %}
      <img class="profile-picture rounded-circle" src="{{ profile.picture.url }}" alt="Picture profile of {{ user }}" />
    {% else %}
      <img class="profile-picture rounded-circle" src="{% static 'img/user_logo.png' %}" alt="Picture profile of {{ user }}" />
    {% endif %}
  </div>
  <div class="post-data ml-2">
    <h3 class="post-user">{{ user }}</h3>
    <span class="post-date">{{ created }}</span>
  </div>
</a>

templates/posts/post.html
{% load static %}
<div class="post">
  <a href="{% url 'posts:post' post.user.username post.id %}" class="post-url"></a>
  {% include "posts/post-content.html" with post=post classes="px-4 pt-4 pb-1" %}
  {% if post.photo %}
    <img class="img-fluid mt-1 rounded post-photo" src="{{ post.photo.url }}" alt="Image blog: {{ post.title }}" />
  {% endif %}
</div>