myFacegram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(("posts.urls", "posts"), namespace="posts")),
    
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(("posts.urls", "posts"), namespace="posts")),
    
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

urlpatterns = [
    path(
        route="",
        view=views.PostsFeedView.as_view(),
        name="feed"
    ),
    path(
        route="posts/new/",
        view=views.CreatePostView.as_view(),
        name="create"
    ),
    path(
        route="posts/<str:username>/<int:id>/",
        view=views.PostDetailView.as_view(),
        name="post"
    ),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path(
        route="login/",
        view=views.login_view,
        name="login"
    ),
    path(
        route="logout/",
        view=views.logout_view,
        name="logout"
    ),
    path(
        route="signup/",
        view=views.signup_view,
        name="signup"
    ),
    path(
        route="profile/update_profile",
        view=views.update_profile_view,
        name="update_profile"
    ),
    path(
        route="profile/<str:username>/",
        view=views.UserProfileView.as_view(),
        name="profile"
    ),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        | myFacegram
      {% endblock %}
    </title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/modules/bootstrap@5.3.3.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/posts/posts.css' %}" />
    <link rel="stylesheet" href="{% static 'css/forms.css' %}" />
  </head>
  <body class="colors concepts entities">
    {% include 'header.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}

    <script src="{% static 'js/modules/bootstrap@5.3.3.bundle.min.js' %}"></script>
    {% block script %}

    {% endblock %}
  </body>
</html>

templates/footer.html
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
{% endblock %}
<footer>
  <div class="footer">
    <div class="element-footer">
      <h5 class="m-0"><a href="https://github.com/stariluz" target="_blank" class="creator">A site of Stariluz.</a></h5>
    </div>
    {% comment %} <div class="element-footer">
      <h3>Navegar</h3>
      <ul>
        <li>
          <a href="#">Home</a>
        </li>
        <li>
          <a href="#">Meme</a>
        </li>
        <li>
          <a href="#">Videos</a>
        </li>
      </ul>
    </div>
    <div class="element-footer">
      <h3>Acerca de nosotros</h3>
      <ul>
        <li>
          <a href="#">¿Quíenes somos?</a>
        </li>
        <li>
          <a href="#">Envíanos un correo</a>
        </li>
        <li>
          <div class="redes">
            <h4>Nuestras redes</h4>
            <ul>
              <li>
                <a href="#" class="red facebook"><img src="https://i.imgur.com/vAWFbXI.png" title="Facebook-logo source: imgur.com" alt="Facebook-logo source: imgur.com" /></a>
              </li>
              <li>
                <a href="#" class="red github"><img src="https://i.imgur.com/IlsMnqX.png" title="Github-logo source: imgur.com" alt="Github-logo source: imgur.com" /></a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
    <div class="element-footer">
      <h3>Documentos</h3>
      <ul>
        <li>
          <a href="#">Terminos y condiciones</a>
        </li>
        <li>
          <a href="#">Politicas de privacidad</a>
        </li>
      </ul>
    </div> {% endcomment %}
  </div>
</footer>

templates/header.html
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/header.css' %}" />
{% endblock %}
<header class="header">
  {% comment %} <navbar class="navbar">
    {% endcomment %}
    <div class="header-fixed">
      <div class="main-container container header-content">
        <section class="header-actions">
          <div class="dropdown">
            <button class="dropdown-toggle profile-picture-container" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="{% if request.user.profile.picture %}
                  {{ request.user.profile.picture.url }}
                {% else %}
                  {% static 'img/user_logo.png' %}
                {% endif %}"
                alt="profile-picture"
                class="profile-picture rounded-circle" />
            </button>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'users:profile' request.user.username %}">
                  <span>Ver perfil</span>
                  <span class="icon">
                    {% include "common/icons/user-square-rounded.html" %}
                  </span>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'users:logout' %}">
                  <span>Cerrar sesion</span>
                  <span class="icon">
                    {% include "common/icons/logout.html" %}
                  </span>
                </a>
              </li>
            </ul>
          </div>
          <a href="{% url 'posts:create' %}">
            <span class="icon">
              {% include "common/icons/square-rounded-plus.html" %}
            </span>
          </a>
        </section>
        <div class="brand">
          <div class="brand-element">
            <h1>olibri</h1>
          </div>
          <div class="brand-element">
            <a href="{% url 'posts:feed' %}"><img src="{% static 'img/logo.png' %}" height="45" class="d-inline-block align-top" /></a>
          </div>
        </div>
      </div>
    </div>
    {% comment %}
  </navbar> {% endcomment %}
</header>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>