myFacegram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(("posts.urls", "posts"), namespace="posts")),
    
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platzigram/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    path("", include(("posts.urls", "posts"), namespace="posts")),
    
    path("users/", include(("users.urls", "users"), namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views

urlpatterns = [
    path(
        route="",
        view=views.PostsFeedView.as_view(),
        name="feed"
    ),
    path(
        route="posts/new/",
        view=views.CreatePostView.as_view(),
        name="create"
    ),
    path(
        route="posts/<str:username>/<int:id>/",
        view=views.PostDetailView.as_view(),
        name="post"
    ),
]

users/urls.py
from django.urls import path
from users import views

urlpatterns = [
    path(
        route="login/",
        view=views.login_view,
        name="login"
    ),
    path(
        route="logout/",
        view=views.logout_view,
        name="logout"
    ),
    path(
        route="signup/",
        view=views.signup_view,
        name="signup"
    ),
    path(
        route="profile/update_profile",
        view=views.update_profile_view,
        name="update_profile"
    ),
    path(
        route="profile/<str:username>/",
        view=views.UserProfileView.as_view(),
        name="profile"
    ),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)

    description=models.TextField(blank=True)
    birthday=models.IntegerField(blank=True,unique_for_date=True,default="0")
    birthmonth=models.IntegerField(blank=True,unique_for_month=True,default="0")
    birthyear=models.IntegerField(blank=True,unique_for_year=True,default="0")

    phone_number=models.CharField(
        max_length=20,
        blank=True
    )
    picture=models.ImageField(
        upload_to='users/pictures',
        null=True
    )

    created= models.DateTimeField(auto_now_add=True)

    modified= models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/forms.py
#Django
from django import forms

from django.contrib.auth.models import User
from users.models import Profile

from django.contrib.auth import authenticate, login

class UpdateProfileForm(forms.Form):
    email=forms.CharField(widget=forms.EmailInput(),required=True)
    first_name=forms.CharField(required=True)
    last_name=forms.CharField(required=True)
    phone_number=forms.CharField(max_length=20, required=True)
    birthday=forms.IntegerField(required=True)
    birthmonth=forms.IntegerField(required=True)
    birthyear=forms.IntegerField(required=True)
    description=forms.CharField(max_length=500, required=True)
    picture=forms.ImageField(required=False)

    def save(self, user, profile):
        data=self.cleaned_data
        user.first_name=data["first_name"]
        user.last_name=data["last_name"]
        user.email=data["email"]
        user.save()
        profile.phone_number=data["phone_number"]
        profile.birthday=data["birthday"]
        profile.birthmonth=data["birthmonth"]
        profile.birthyear=data["birthyear"]
        profile.description=data["description"]
        if data["picture"]:
            profile.picture=data["picture"]
        profile.save()

class SignupForm(forms.Form):
    username= forms.CharField(min_length=4, max_length=50)
    password=forms.CharField(widget=forms.PasswordInput())
    password_confirmation=forms.CharField(widget=forms.PasswordInput())

    first_name=forms.CharField(required=True)
    last_name=forms.CharField(required=True)
    email=forms.CharField(widget=forms.EmailInput())
    
    def clean(self):
        data=super().clean()
        password=data['password']
        username=data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username is already in use.")
        password_confirmation=data['password_confirmation']
        if password!=password_confirmation:
            raise forms.ValidationError("Passwords do not match.")
        return data
    
    def save(self, request):
        data=self.cleaned_data
        data.pop("password_confirmation")

        user=User.objects.create_user(**data)
        user.save()
        profile=Profile(user=user)
        profile.save()
        login(request, user)

class LoginForm(forms.Form):
    username=forms.CharField(required=True)
    password=forms.CharField(required=True)
    
    def clean(self):
        data=super().clean()
        username=data['username']
        password=data['password']

        user_exists=User.objects.filter(username=username).exists()
        user=authenticate(self, username=username, password=password)
        
        #Validate if user exists
        if not user_exists:
            raise forms.ValidationError("User does not exist")
        #Validate if user is authenticate
        if not user:
            raise forms.ValidationError('The username or password is incorrect')
        return data

    def save(self, request):
        data=self.cleaned_data
        username=data['username']
        password=data['password']
        user=authenticate(self, username=username, password=password)
        login(request, user)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView,TemplateView, FormView, UpdateView
from django.contrib.auth.models import User
from django.urls import reverse_lazy

from users.models import Profile
from posts.models import Post
#Forms
from users.forms import UpdateProfileForm, SignupForm, LoginForm

from users.my_functions import error_form_list

class UserProfileView(LoginRequiredMixin, DetailView):
    """User profile view."""
    template_name="users/profile.html"
    slug_field='username'
    slug_url_kwarg='username'
    queryset=User.objects.all()
    context_object_name="user"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user=self.get_object()
        context["posts"] = Post.objects.filter(user=user).order_by("-created")
        return context


class LoginView(auth_views.LoginView):
    template_name="users/login.html"
    
# Views functions
def login_view(request):
    if request.method == 'POST':
        form=LoginForm(request.POST)
        if form.is_valid():
            form.save(request)
            return redirect("posts:feed")
        else:
            list_errors=error_form_list(str(form.errors))
            
    else:
        form=LoginForm()
        list_errors=[]
    
    context={
        "form": form,
        "errors": list_errors,
    }
    return render(request, 'users/login.html', context)

@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')

""" 
class SignupView(FormView):
    template_name="users/signup.html"
    form_class=SignupForm
    success_url=reverse_lazy("posts:feed")
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["errors"] = error_form_list(str(self.form_class.errors))
        return context
    
    def form_valid(self, form):
        form.save(self.request)
        return super().form_valid(form)
"""

def signup_view(request):
    
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid():
            form.save(request)
            return redirect('users:login')
        else:
            list_errors=error_form_list(str(form.errors))
            ###print(list_errors)
    else:
        form=SignupForm()
        list_errors=[]

    context={
        "form": form,
        "errors": list_errors,
    }
        
    return render(request, 'users/signup.html', context)

@login_required
def update_profile_view(request):

    user=request.user
    profile=user.profile
    form=UpdateProfileForm()

    errors=[]
    if request.method=='POST':
        form=UpdateProfileForm(request.POST, request.FILES)
        if (not profile.picture) and (not request.FILES):
            errors.append("Please enter an picture")
        else:
            if form.is_valid():
                form.save(user, profile)
                return redirect("users:update_profile")
        
    if len(errors)==0:
        errors=False
    context={
        'profile': profile,
        'user': user,
        'form': form,
        'errors': errors,
    }
    return render(request, 'users/update_profile.html', context)

templates/users/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            myFacegram
        {% endblock %}
    </title>
    
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/auth/sesion.css' %}" />
</head>
<body class="colors concepts entities">
    <div class="header-padding"></div>
    <div class="container main-container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            myFacegram
        {% endblock %}
    </title>
    
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sesion.css' %}" />
</head>
<body>
    <div class="header-padding"></div>
    <div class="container principal-container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/users/login.html
{% extends 'users/auth.html' %}

{% block title %}
    Log In | myFacegram
{% endblock title %}

{% block content %}
    <div class="container auth-container">
        {% for item in errors %}
            {% for error in item %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endfor %}
        {% load static %}
        <div class="auth-container-header">
            <img class="" src="{% static 'img/user_logo.png'%}" alt="" width="72" height="72">
            <h1 class="auth-title">Log in!</h1>
        </div>
        <form method="POST" action="{% url 'users:login' %}">
            {% csrf_token %}
            {% if error %}
                <p style="color: red;"> {{ error }}</p>
            {% endif %}
            <div class="form-group">
                <input class="form-control" type="text" placeholder="Username" name="username">
                <input class="form-control" type="password" placeholder="Password" name="password">  
            </div>
            <div class="checkbox mb-3">
                <label>
                <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">Log in</button>
        </form>
        <div class="mb-3">
            <span class="">
                Don't have an account yet? <a href="{% url 'users:signup' %}">Sign up</a>
            </span>
        </div>
    </div>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
  @{{ user.username }} | Profile {{ block.super }}
{% endblock %}

{% load static %}

{% block content %}
  {% block css %}
    <link rel="stylesheet" href="{% static 'css/posts/posts-grid.css' %}" />
    <link rel="stylesheet" href="{% static 'css/users/profile.css' %}" />
  {% endblock %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-3 position-relative">
        <div class="profile-container-fixed">
          <div class="profile-container">
            <div class="profile-picture-container picture-big">
              <img src="{% if user.profile.picture %}
                  {{ user.profile.picture.url }}
                {% else %}
                  {% static 'img/user_logo.png' %}
                {% endif %}"
                alt="{{ user.first_name }}"
                class="profile-picture rounded-circle"
                id="profile-picture-{{ user.pk }}" />
            </div>
            <div class="profile-header">
              <h1 class="h6 pb-0 mb-0">@{{ user.username }}</h1>
              <h1 class="h6 pb-0 mb-0">{{ user.first_name }} {{ user.last_name }}</h1>
              <label>{{ user.profile.description }}</label>
            </div>
          </div>
        </div>
      </div>
      <div class="col-9">
        <div class="container">
          <section class="posts-grid">
            {% for post in posts %}
              <article class="post-container">
                {% include 'posts/post.html' with post=post %}
              </article>
            {% endfor %}
          </section>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  {{ block.super }}
  <script src="{% static 'js/modules/minimasonry.js' %}" type="module"></script>
  <script src="{% static 'js/posts/masonry.js' %}" type="module"></script>
{% endblock %}

templates/users/signup.html
{% extends 'users/auth.html' %}

{% block title %}
    Sign up | myFacegram
{% endblock title %}

{% load static %}
{% block content %}
    <div class="container auth-container">
        {% for item in errors %}
            {% for error in item %}
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endfor %}
        <div class="auth-container-header">
            <img class="" src="{% static 'img/user_logo.png'%}" alt="" width="72" height="72">
            <h1 class="auth-title">Sign up!</h1>
        </div>

        <form method="POST" action="{% url 'users:signup' %}">
            {% csrf_token %}

            <div class="form-group">
                <input class="form-control
                {% if form.username.errors %}
                  is-invalid
                {% endif %}
                " type="text" placeholder="Username" name="username" required="true" value="{% if form.errors %}{{ form.username.value }}{% endif %}">
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                        {{ error }} 
                    {% endfor %}
                </div>

                <input class="form-control
                {% if form.password.errors %}
                  is-invalid
                {% endif %}
                " type="password" placeholder="Password" name="password" required="true" value="{% if form.errors %}{{ form.password.value }}{% endif %}"> 
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                        {{ error }} 
                    {% endfor %}
                </div> 
            </div>

            <div class="form-group">
                <input class="form-control
                {% if form.password_confirmation.errors %}
                  is-invalid
                {% endif %}
                " type="password" placeholder="Password confirmation" name="password_confirmation" required="true" value="{% if form.errors %}{{ form.password_confirmation.value }}{% endif %}">
                <div class="invalid-feedback">
                    {% for error in form.password_confirmation.errors %}
                        {{ error }} 
                    {% endfor %}
                </div>

            </div>

            <div class="form-group">
                <input class="form-control
                {% if form.first_name.errors %}
                  is-invalid
                {% endif %}
                " type="text" placeholder="First name" name="first_name" required="true" value="{% if form.errors %}{{ form.first_name.value }}{% endif %}">
                <div class="invalid-feedback">
                    {% for error in form.first_name.errors %}
                        {{ error }} 
                    {% endfor %}
                </div>

                <input class="form-control
                {% if form.last_name.errors %}
                  is-invalid
                {% endif %}
                " type="text" placeholder="Last name" name="last_name" required="true" value="{% if form.errors %}{{ form.last_name.value }}{% endif %}">
                <div class="invalid-feedback">
                    {% for error in form.last_name.errors %}
                        {{ error }} 
                    {% endfor %}
                </div>
            </div>

            <div class="form-group">
                <input class="form-control
                {% if form.email.errors %}
                  is-invalid
                {% endif %}
                " type="text" placeholder="Email addres" name="email" required="true" value="{% if form.errors %}{{ form.email.value }}{% endif %}">
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        {{ error }} 
                    {% endfor %}
                </div>
            </div>

            <div class="checkbox mb-3">
                <label>
                <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>

            <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">Sign up</button>

        </form>
        <div class="mb-3">
            <span class="">
                Do you already have an account? <a href="{% url 'users:login' %}">Log in!</a>
            </span>
        </div>
    </div>
{% endblock content %}

templates/users/update_profile.html
{% extends 'base.html' %}

{% block title %}
  @{{ user.username }} | Update Profile {{ block.super }}
{% endblock title %}


{% load static %}

{% block content %}
  {% comment %} <div class="container-update-profile"> {% endcomment %}
    <form method="POST" action="{% url 'users:update_profile' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row">
        <div class="col col-lg-6 offset-lg-3">
          <div class="user-data">
              {% if errors %}
                {% for error in errors %}
                  <div class="alert alert-danger text-center">
                    {{ error }}
                  </div>
                {% endfor %}
              {% endif %}
              <div class="profile-picture picture-big m-auto" onmouseover="ProfileOverImage('profile-picture-{{user.pk}}')" onmouseout="ProfileOutImage('profile-picture-{{user.pk}}-hover')">
                <div class="hover-img justify-content-center align-items-center rounded-circle" id="profile-picture-{{user.pk}}-hover" >
                  <div class="input-group">
                    <div class="custom-file justify-content-center">
                    <input type="file" class="custom-file-input {% if form.picture.errors %}is-invalid{% endif %}" id="picture-{{ user.pk }}" aria-describedby="picture-{{ user.pk }}" name="picture" onchange="setFileName('picture-{{ user.pk }}')">
                    <label class="custom-file-label" id="picture-{{ user.pk }}-label">Change photo...</label>
                    </div>
                  </div>
                </div>
                <div class="embed-responsive embed-responsive-1by1">
                  <img src="{% if profile.picture %}{{ profile.picture.url }}{% else %}{% static 'img/user_logo.png' %}{% endif %}" alt="{{ user.first_name }}" class="embed-responsive-item rounded-circle" id="profile-picture-{{user.pk}}" >
                </div>
              </div>
              <div class="text-center">
                <h2>@{{ user.username }}</h2>
                <div class="form-group row">
                  <div class="col">
                    <input type="text" class="form-control {% if form.first_name.errors %} is-invalid {% endif %}"  id="first_name" name="first_name" value="{% if form.errors or errors%}{{ form.first_name.value }}{% else %}{{ user.first_name }}{% endif %}">
                    <div class="invalid-feedback text-left">
                      {% for error in form.first_name.errors %}
                        {{ error }}
                      {% endfor %}
                    </div>
                  </div>
                  <div class="col">
                    <input type="text" class="form-control {% if form.last_name.errors %} is-invalid {% endif %}"  id="last_name" name="last_name" value="{% if form.errors or errors%}{{ form.last_name.value }}{% else %}{{ user.last_name }}{% endif %}">
                    <div class="invalid-feedback text-left">
                      {% for error in form.last_name.errors %}
                        {{ error }}
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
              <div class="">
                <div class="form-group">
                  <h6 class="d-inline">Email: </h6>
                  <input type="text" class="form-control {% if form.email.errors %} is-invalid {% endif %}"  id="email" name="email" value="{% if form.errors or errors%}{{ form.email.value }}{% else %}{{ user.email }}{% endif %}">
                  <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <h6 class="d-inline">Birthday: </h6>
                  <div class="row">
                    <div class="col">
                      <small id="birthday-help" class="form-text text-muted">Day</small>
                      <input type="text" class="form-control {% if form.birthday.errors %} is-invalid {% endif %}" id="birthday" name="birthday" value="{% if form.errors %}{{ form.birthday.value }}{% else %}{{ profile.birthday }}{% endif %}">
                      <div class="invalid-feedback">
                        {% for error in form.birthday.errors %}
                          {{ error }}
                        {% endfor %}
                      </div>
                    </div>
                    <div class="col">
                      <small id="birthmonth-help" class="form-text text-muted">Month</small>
                      <input type="text" class="form-control {% if form.birthmonth.errors %} is-invalid {% endif %}" id="birthmonth" name="birthmonth" value="{% if form.errors %}{{ form.birthmonth.value }}{% else %}{{ profile.birthmonth}}{% endif %}">
                      <div class="invalid-feedback">
                        {% for error in form.birthmonth.errors %}
                          {{ error }}
                        {% endfor %}
                      </div>
                    </div>
                    <div class="col">
                      <small id="birthyear-help" class="form-text text-muted">Year</small>
                      <input type="text" class="form-control {% if form.birthyear.errors %} is-invalid {% endif %}" id="birthyear" name="birthyear" value="{% if form.errors %}{{ form.birthyear.value }}{% else %}{{ profile.birthyear }}{% endif %}">
                      <div class="invalid-feedback">
                        {% for error in form.birthyear.errors %}
                          {{ error }}
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <h6 class="d-inline">Phone number: </h6>
                  <input type="text" class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"  id="phone_number" name="phone_number" value="{% if form.errors or errors%}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}">
                  <div class="invalid-feedback">
                    {% for error in form.phone_number.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <label for="">Description: </label>
                  <textarea class="form-control {% if form.description.errors %} is-invalid {% endif %}" name="description" id="description" style="height:120px; resize:none;" placeholder="Says something about you..."
                  >{% if form.errors or errors%}{{ form.description.value }}{% else %}{{ profile.description }}{% endif %}</textarea>
                  <div class="invalid-feedback">
                      {% for error in form.description.errors %}
                        {{ error }}
                      {% endfor %}
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </div>
    </form>
  {% comment %} </div> {% endcomment %}
{% endblock content %}
{% block script %}
  {{ block.super }}
  <script src="{% static 'js/label_name.js' %}"></script>
  <script src="{% static 'js/update_profile.js' %}"></script>
{% endblock script %}